AthanorLabs/atomic-swap

README.md, alice/swap_state.go, alice/swap_state_test.go, bob/protocol.go, bob/swap_state.go, bob/swap_state_test.go, cmd/daemon/main.go, monero/client.go, monero/client_test.go, monero/crypto.go, monero/rpc.go, net/initiate.go, scripts/run-unit-tests.sh
=> add view key checks using open_wallet and close_wallet

README.md, alice/net.go, alice/protocol.go, alice/swap_state.go, bob/net.go, bob/protocol.go, bob/swap_state.go, cmd/client/discover.go, cmd/client/initiate.go, cmd/client/main.go, cmd/client/query.go, cmd/daemon/main.go, common/provides.go, common/utils.go, go.mod, go.sum, monero/client.go, monero/daemon.go, monero/keys.go, monero/rpc.go, monero/rpc_util.go, monero/utils.go, net/discovery.go, net/host.go, net/message.go, net/query.go, rpc/net.go, rpcclient/utils.go
implement swapcli, example usage:
```
$ ./swapcli discover --provides XMR --search-time 3
[[/ip4/192.168.0.101/tcp/9934/p2p/12D3KooWHLUrLnJtUbaGzTSi6azZavKhNgUZTtSiUZ9Uy12v1eZ7 /ip4/127.0.0.1/tcp/9934/p2p/12D3KooWHLUrLnJtUbaGzTSi6azZavKhNgUZTtSiUZ9Uy12v1eZ7 /ip4/38.88.101.233/tcp/48161/p2p/12D3KooWHLUrLnJtUbaGzTSi6azZavKhNgUZTtSiUZ9Uy12v1eZ7]]
```
```
$ ./swapcli query --multiaddr /ip4/192.168.0.101/tcp/9934/p2p/12D3KooWHLUrLnJtUbaGzTSi6azZavKhNgUZTtSiUZ9Uy12v1eZ7
Provides: [XMR]
MaximumAmount: [1]
ExchangeRate (ETH/XMR): 0.0578261
```
```
$ ./swapcli initiate --multiaddr /ip4/192.168.0.101/tcp/9934/p2p/12D3KooWHLUrLnJtUbaGzTSi6azZavKhNgUZTtSiUZ9Uy12v1eZ7 --provides ETH --provides-amount 100000000000000000 --desired-amount 1000000000
```
closes #20
=> implement swapcli

alice/net.go, alice/protocol.go, alice/swap_state.go, alice/swap_state_test.go, bob/net.go, bob/protocol.go, bob/swap_state.go, bob/swap_state_test.go, cmd/client/initiate.go, cmd/client/main.go, cmd/daemon/main.go, common/consts.go, monero/utils.go, net/host.go, net/message.go, rpc/net.go, rpcclient/utils.go
=> update units passed by cli/RPC to be standard unts, not smallest denomination

alice/protocol.go, alice/swap_state.go, alice/swap_state_test.go, bob/protocol.go, bob/swap_state.go, bob/swap_state_test.go, cmd/client/main.go, monero/client.go, monero/client_test.go, monero/crypto/address.go, monero/crypto/base58.go, monero/crypto/crypto.go, monero/crypto/crypto_test.go, monero/crypto/hash.go, monero/crypto/sign.go, monero/crypto/sign_test.go, monero/crypto/write.go, monero/rpc.go, monero/rpc_test.go, monero/utils.go, net/message.go, rpc/net.go, swap-contract/swap_test.go, swap-contract/utils.go, swap-dleq-contract/swap_dlep_test.go
=> add private key proof to SendKeyMessage, verify on receipt

docs/rpc.md, rpc/net.go
=> add json-rpc documentation

go.mod, go.sum, rpc/server.go
@Tbaut pls try and let me know if this works!
=> add CORS support

crypto/hash.go, docs/rpc.md, net/host.go, protocol/alice/swap_state.go, protocol/bob/swap_state.go, rpc/net.go, rpc/server.go
implement `net_takeOfferSync` which returns the swap status only after the swap completes.
=> implement `net_takeOfferSync`

cmd/client/client/swap.go, cmd/client/main.go, net/message/message.go, protocol/alice/errors.go, protocol/alice/instance.go, protocol/alice/message_handler.go, protocol/alice/recovery.go, protocol/alice/swap_state.go, protocol/alice/swap_state_test.go, protocol/bob/swap_state.go, rpc/server.go, rpc/swap.go
=> implement `swap_refund` endpoint

cmd/client/client/swap.go, cmd/client/main.go, common/interfaces.go, net/message/message.go, protocol/alice/instance.go, protocol/alice/swap_state.go, protocol/bob/instance.go, protocol/bob/swap_state.go, protocol/stage.go, rpc/server.go, rpc/swap.go
=> implement `swap_getStage`

crypto/secp256k1/secp256k1.go, dleq/cgo_dleq.go, dleq/cgo_dleq_test.go, go.mod, go.sum, protocol/common.go, scripts/install-monero-linux.sh, scripts/run-integration-tests.sh, scripts/run-unit-tests.sh, scripts/setup-env.sh, scripts/setup-stagenet.sh
migrate to dleq-rs library (https://github.com/kayabaNerve/dleq-rs/tree/develop) using cgo bindings provided here: https://github.com/noot/cgo-dleq
=> migrate to dleq-rs library

cmd/daemon/main.go, cmd/daemon/main_test.go, cmd/recover/main.go, cmd/recover/main_test.go, cmd/tester/main.go, common/rpcclient/wsclient.go, monero/utils.go, monero/utils_test.go, protocol/alice/instance.go, protocol/alice/message_handler.go, protocol/alice/recovery.go, protocol/alice/recovery_test.go, protocol/alice/swap_state.go, protocol/bob/message_handler.go, protocol/bob/offers.go, protocol/bob/swap_state.go, recover/recovery.go, recover/recovery_test.go, rpc/server.go, rpc/ws.go, scripts/run-integration-tests.sh, scripts/setup-stagenet.sh
fixes concurrency issues w/ automated tester
=> automated tester improvements and fixes

protocol/bob/errors.go, protocol/bob/message_handler.go, protocol/bob/utils.go, protocol/bob/utils_test.go
=> implement checkContractCode to check that contact is valid

net/filters.go
=> fix private IP filters

ethereum/deploy_util.go, ethereum/deploy_util_test.go
Code now checks if the domain separator is registered before registering.
=> check if the domain separator is registered before registering

cmd/swapcli/main.go
=> implement get-offers for swapcli

net/discovery.go, net/host.go
=> implement discoverLoop to find peers if count is low

docs/local.md
I was deploying locally following the local.md instructions and found a few things that needed to be updated
=> Updated local.md

.gitignore, ui/package.json, ui/rollup.config.js, ui/src/utils/rpcApi.ts
My 1st contribution. Looking forward to see your comments.
=> ui: make swapd ports configurable

go.mod, go.sum
small fix was added to the go-dleq lib
=> bump go-dleq version

common/types/offer.go, common/types/offer_test.go
- update offer type to have nonce
- update offer ID to be hash of all its field
- add ID validation on json unmarshalling; unmarshal will fail if the hash of the fields isn't the same as the ID provided
closes #273
=> fix: update offer ID to be hash of offer fields

cmd/swapcli/main.go, common/rpctypes/types.go, common/types/status.go, common/types/status_test.go, db/database_test.go, protocol/swap/types_test.go, rpc/net.go, rpc/swap.go, rpc/ws.go, rpcclient/wsclient/wsclient.go
Adds JSON marshaling support to our Status type and converts serialized data structures to use it directly.
=> added JSON marshaling support to the Status type

.github/workflows/unit-tests.yml, .gitignore, codecov.yml, scripts/run-unit-tests.sh, tests/integration_test.go
=> switch to codecov-action@v3 for uploading code coverage

cmd/swapcli/main.go, docs/local.md, docs/stagenet.md
=> Make subscribing the default behavior with --detached

go.mod, go.sum
related to #326 
nothing new was added to those repos, just tagged the latest commit :)
=> update go-relayer and go-dleq deps

common/types/ethasset.go, common/types/offer_test.go, protocol/xmrmaker/net.go, protocol/xmrtaker/message_handler.go, protocol/xmrtaker/net.go, protocol/xmrtaker/swap_state.go, relayer/validate_test.go
tested ERC20s on stagenet/sepolia, they worked :D just added a few minor logging updates.
related to #326
=> log updates for ERC20 swaps

cmd/swapcli/main.go, daemon/swap_daemon.go, daemon/swap_daemon_test.go, rpc/daemon.go, rpc/mocks_test.go, rpc/server.go, rpcclient/daemon.go
=> swapd version & shutdown

Dockerfile
This is a PR to `noot/docker`, not a PR directly to `master`.
=> dockerfile adjustments

bootnode/bootnode.go, daemon/swap_daemon.go
=> fix: handle RPC server panic if port is in use

cmd/bootnode/main.go, cmd/swapcli/main.go, cmd/swapd/contract.go, cmd/swapd/main.go, common/config.go, docs/build.md, docs/mainnet.md, ethereum/deploy_util.go, scripts/docker-bootnode/run-docker-image.sh, scripts/run-integration-tests.sh
mainnet :D
```
./bin/swapd --env mainnet --eth-endpoint=your-endpoint
```
or just 
```
./bin/swapd --eth-endpoint=your-endpoint
```
#326
=> release: mainnet contract address, set env defaults to mainnet

net/host_test.go, net/relay.go, net/relay_test.go, net/types.go, protocol/backend/backend.go, protocol/swap/manager.go, protocol/swap/types.go, rpc/mocks_test.go
=> fix: move counterparty-relay checks to backend

daemon/double_restart_test.go, protocol/claim_monero.go, protocol/swap/types.go, protocol/xmrmaker/message_handler.go, protocol/xmrmaker/swap_state_test.go, protocol/xmrtaker/message_handler.go, protocol/xmrtaker/swap_state.go, protocol/xmrtaker/swap_state_test.go
=> fix: fix swap status channel setting on restart

Makefile, cliutil/utils.go, docs/local.md, scripts/multi-platform-release-build.sh
Added Makefile targets to build the latest tagged release.
=> makefile targets for release binaries

coins/common.go, common/types/offer_test.go, docs/mainnet.md, docs/rpc.md, relayer/submit_transaction_test.go, relayer/validate.go, relayer/validate_test.go, tests/integration_test.go
as title says, this makes the break-even gas price around 117.5 gwei.
related to #430
=> bump relayer fee to 0.01

cmd/swapcli/main.go, protocol/xmrmaker/claim.go, protocol/xmrmaker/errors.go
Renamed `waitForClaimReceipt` to `waitForClaimRelayerReceipt` and added fixes.
=> wait for claim relayer receipt

cmd/swapcli/main.go, ethereum/extethclient/eth_wallet_client.go, protocol/backend/backend.go, rpc/mocks_test.go, rpc/personal.go, rpc/server.go, rpcclient/personal.go
- implement transfer-xmr, sweep-xmr, and transfer-eth methods for swapcli
- easier to transfer funds now :)
=> feat: add transfer methods to swapcli

protocol/xmrmaker/instance.go
=> fix: take offer when recreating ongoing swap

docs/build.md, docs/rpc.md, scripts/docker-bootnode/Dockerfile, scripts/docker-swapd/Dockerfile
Changes:
* Updates build.md with details on building release binaries
* Updates rpc.md with undocumented `swap_clearOffers` method
* Updates base docker images from bullseye to bookworm
Feel free to hit the edit button on these links to make direct changes to this PR.
* https://github.com/AthanorLabs/atomic-swap/blob/dimalinux/doc-updates/docs/build.md
* https://github.com/AthanorLabs/atomic-swap/blob/dimalinux/doc-updates/docs/rpc.md
=> doc updates
