alice/protocol.go, alice/swap_state.go, bob/protocol.go, bob/swap_state.go, common/utils.go, monero/client.go, monero/client_test.go, monero/crypto.go, monero/rpc.go, monero/utils.go, swap-contract/swap_test.go
- wait for receipts instead of instantly retrieving them (as they aren't immediately available on a real chain)
- wait for monero blocks after transferring
=> fixes for stagenet + ropsten

README.md, cmd/client/client/swap.go, cmd/client/client/take_offer.go, cmd/client/main.go, cmd/daemon/main.go, docs/developing.md, docs/rpc.md, net/host.go, net/initiate.go, net/message.go, protocol/alice/instance.go, protocol/alice/message_handler.go, protocol/alice/net.go, protocol/alice/swap_state.go, protocol/alice/swap_state_test.go, protocol/bob/instance.go, protocol/bob/message_handler.go, protocol/bob/net.go, protocol/bob/recovery_test.go, protocol/bob/swap_state.go, protocol/bob/swap_state_test.go, protocol/swap/manager.go, rpc/net.go, rpc/server.go, rpc/swap.go, tests/integration_test.go
closes #71
- implement `swap_getPastIDs`
- implement `swap_getPast`
- implement `swap_getOngoing`
- update `net_takeOffer` to return swap ID on swap initiation (instead of success bool on completion)
todo:
=> implement `swap_` rpc service to allow for fetching of current/past swap statuses

net/message/message.go, protocol/alice/message_handler.go, protocol/alice/net.go, protocol/alice/net_test.go, protocol/alice/recovery_test.go, protocol/alice/swap_state.go, protocol/alice/swap_state_test.go, protocol/bob/swap_state_test.go, protocol/swap/manager.go, rpc/net.go, rpc/server.go, rpc/ws_test.go
update Alice (ETH holder) to accept a `*types.Offer` when initiating the swap, so that she can check that the amount the counterparty claims they will send in the `*SendKeysMessage` is what she expected to receive.
closes #98
=> check that XMR amount peer will send is same as expected 

ui/src/App.svelte, ui/src/stores/peerStore.ts, ui/src/utils/sanitizeAddresses.ts
previously was filtering out peers other than the first
=> ui: display multiple peers

protocol/xmrmaker/message_handler.go, protocol/xmrmaker/swap_state.go, protocol/xmrtaker/message_handler.go, protocol/xmrtaker/swap_state.go, protocol/xmrtaker/swap_state_test.go, recover/recovery_test.go, tests/monero_wallet_rpc.go
* Fixes an issue in `handleNotifyXMRLock` where the `swapState` lock could be grabbed twice after T1 expires
* Changes the lock in both `swapState` structs to be explicit (making the code easier to audit)
* Moves the T0 and T1 expiration code into dedicated functions for readability (verses having them in long code blocks inside a switch of an inline go process)
* Increased mined blocks by `TestSwapState_NotifyClaimed` (was still flaky and occasionally running out of money with only 60 blocks)
* Reaps exited monero-wallet-rpc processes immediately instead of when testing for a package completes
* Change to `TestRecoverer_RecoverFromXMRMakerSecretAndContract_Claim_afterTimeout` to call `set_ready`
=> Fix double locks

common/utils.go, common/utils_test.go, crypto/secp256k1/secp256k1.go, dleq/cgo_dleq_test.go, monero/client.go, monero/daemon.go, net/host.go, protocol/xmrmaker/recovery.go, protocol/xmrtaker/recovery.go, recover/recovery.go, scripts/install-lint.sh, swapfactory/swap_factory_test.go
On occasion we were getting transactions reverted with `provided secret does not match the expected public key`. It was a padding issue when we were converting X/Y in big.Int format when X or Y had less than 32 bytes.  The array was in big endian format and we were shifting the value left by however many high order bytes were all zero. This PR fixes the issue.
=> fix incorrect padding in NewPublicKeyFromBigInt

cmd/client/main.go, protocol/xmrmaker/offers.go, rpc/server.go, rpc/swap.go, rpcclient/swap.go, scripts/run-integration-tests.sh, tests/integration_test.go
- implement `swap_clearOffers` which can clear some or all offers
- use in integration tests
i think this implicitly closes #145 also since we never actually pinned the version, lol.
=> implement `swap_clearOffers` endpoint for usage in integration tests

cmd/client/main.go, common/rpctypes/types.go, docs/rpc.md, rpc/net.go, rpcclient/discover.go
implement `net_queryAll` method to discover peers making offers on the network and also get those offers in one command (instead of needing to do `discover` and `query` separately)
closes #119
=> implement `net_queryAll` method

protocol/backend/backend.go, protocol/txsender/sender.go, protocol/txsender/tx_opts.go
add wrapped `TxOpts` type to fix multiple txsender concurrency issues, since the last PR (#158) made it so that the txsender was per-swap instead of global.
=> fix: add wrapped TxOpts type

cmd/client/main.go, cmd/daemon/main.go, cmd/daemon/main_test.go, cmd/recover/main.go, common/coins.go, common/coins_test.go, docs/local.md, docs/rpc.md, docs/stagenet.md, monero/wallet_client_test.go, net/discovery.go, protocol/xmrmaker/errors.go, rpc/mocks_test.go, rpc/net.go, rpc/server.go, rpc/ws_test.go, rpcclient/wsclient/wsclient.go, scripts/run-integration-tests.sh, testerconfig.json, tests/integration_test.go, ui/README.md, ui/src/components/TakeDealDialog.svelte
This PR combines our HTTP RPC and Websocket services into a single HTTP server, eliminating the `--ws-port` flag to `swapd`.  This lowers end-user complexity, especially when running multiple `swapd` servers on one host.  `swapcli` subscribe interactions are fixed with this PR and the `--daemon-addr http://127.0.0.1:PORT` flag to `swapcli` was removed. Instead of passing separate http and websocket URLs to `swapcli`, `swapcli` commands now use `--swapd-port PORT_NUM` allowing `swapcli` to interact with both services, while only requiring one flag from the end user.
=> RPC and WS endpoints share the same port

cmd/swapd/main.go, cmd/swaprecover/main.go, protocol/backend/backend.go, protocol/backend/backend_test.go, protocol/utils.go, protocol/xmrmaker/backend_offers.go, protocol/xmrmaker/claim.go, protocol/xmrmaker/event_test.go, protocol/xmrmaker/instance.go, protocol/xmrmaker/message_handler.go, protocol/xmrmaker/net.go, protocol/xmrmaker/recovery_test.go, protocol/xmrmaker/swap_state.go, protocol/xmrmaker/swap_state_test.go, protocol/xmrtaker/event_test.go, protocol/xmrtaker/instance.go, protocol/xmrtaker/message_handler.go, protocol/xmrtaker/net.go, protocol/xmrtaker/recovery.go, protocol/xmrtaker/recovery_test.go, protocol/xmrtaker/swap_state.go, protocol/xmrtaker/swap_state_test.go, rpc/mocks_test.go, rpc/personal.go, rpc/server.go, rpc/ws.go
This PR isn't for merging into the `dimalinux/rework-backend-wallet-interfaces` branch, not directly into `master`. Look at the diffs and see which one you like best.
=> renamed backend functions ETH to ETHClient and XMR to XMRClient

cmd/swapcli/main.go, cmd/swapd/main_test.go, coins/coins.go, coins/coins_test.go, crypto/monero/crypto.go, monero/test_support.go, monero/utils.go, monero/utils_test.go, monero/wallet_client.go, monero/wallet_client_test.go, protocol/swap/manager.go, protocol/xmrmaker/backend_offers.go, protocol/xmrmaker/instance.go, protocol/xmrmaker/instance_test.go, protocol/xmrmaker/swap_state.go, protocol/xmrmaker/swap_state_test.go, protocol/xmrmaker/utils.go, protocol/xmrtaker/claim.go, protocol/xmrtaker/event_test.go, protocol/xmrtaker/instance.go, protocol/xmrtaker/instance_test.go, protocol/xmrtaker/message_handler.go, protocol/xmrtaker/swap_state.go, protocol/xmrtaker/swap_state_test.go, rpc/mocks_test.go
This PR creates a new `monero-wallet-rpc` instance for temporary swap wallets. This eliminates the need for monero wallet locking, as `monero-wallet-rpc` instances now never switch between wallets. They just use one wallet from the time they are created until they are closed. Simultaneous transactions from the same primary wallet for different swaps is safe. We only required the locking to prevent wallet switching.
=> reduce monero wallet contention

cmd/relayer/validate.go, cmd/relayer/validate_test.go, coins/coins.go, pricefeed/pricefeed_test.go, protocol/xmrmaker/claim.go, protocol/xmrmaker/claim_test.go
* When checking conditions after an APD (arbitrary precision decimal) math operation, `Rounded` is set even when zeros are chopped from a coefficient. Our checks needed to check for `Inexact` instead.
* `calculateRelayerCommission` now rounds the returned relayer commission to the nearest whole Wei value.
* Updated our pricefeed tests to read environment variable for the ETH mainnet endpoint if set
=> rounding fixes

.github/workflows/integration-tests.yaml, .github/workflows/unit-tests.yml, Makefile, pricefeed/pricefeed_test.go, protocol/backend/mock_recovery_db.go, protocol/xmrmaker/offers/mocks.go
This PR should significantly decrease 2 common CI failures:
(1) Issues downloading the monero binaries (we now cache them). This also reduces build time and bandwidth costs for the monero community.
(2) We use a reliable mainnet endpoint from a github actions secret for unit tests that require it.
This PR also switches us from `go fmt` to `go imports` for formatting the code.
=> cache monero download

cmd/swapcli/main.go, docs/rpc.md, protocol/swap/manager.go, protocol/swap/types.go, protocol/swap/types_test.go, protocol/xmrmaker/instance.go, protocol/xmrtaker/instance.go, rpc/swap.go, rpcclient/swap.go
-  add start/end times to `swap.Info`
- update `swap_getPastIDs` to return start/end times also and sort by start time
- update other swap RPC getters to return swap start times
- also update `swap_getOngoing` to return all ongoing swaps if no ID is provided
closes #222
=> feat: add start/end times to `swap.Info` and swap RPC returns

protocol/xmrmaker/net.go, protocol/xmrmaker/offers/offer_manager.go
Previously, xmrmaker recovery of an ongoing swap would fail, because it attempts to get the offer from the db (which it needs), but it was already deleted on swap initiation, causing the daemon to be unable to start up. Now the offer is just deleted from memory (so no one else can take it), but not from the db, so we can still get it on recovery.
=> fix xmrmaker initiation + recovery, don't delete offer from db

cmd/relayer/main.go, cmd/relayer/validate.go, cmd/relayer/validate_test.go, cmd/swapcli/errors.go, cmd/swapcli/main.go, common/consts.go, common/rpctypes/types.go, common/types/offer.go, db/recovery_db_test.go, docs/rpc.md, protocol/xmrmaker/backend_offers.go, protocol/xmrmaker/claim.go, protocol/xmrmaker/claim_test.go, protocol/xmrmaker/errors.go, protocol/xmrmaker/instance_test.go, protocol/xmrmaker/offers/offer_manager.go, protocol/xmrmaker/swap_state.go, rpc/net.go, rpc/server.go, rpcclient/make_offer.go, rpcclient/wsclient/wsclient.go, tests/integration_test.go, tests/relayer_integration_test.go
- update relayer fee to be a fixed value instead of swap percentage
- update default fee to be 0.009 ETH 
- change all usages of `relayerCommission` -> `relayerFee`
closes #293
=> update relayer fee to be fixed at 0.009 ETH

protocol/xmrmaker/event.go, protocol/xmrmaker/swap_state.go, protocol/xmrtaker/event.go, protocol/xmrtaker/swap_state.go
I encountered a bug when testing where if the counterparty exits the swap while the xmrmaker is locking funds, the protocol aborts on the xmrmaker side when it shouldn't (because funds were already locked). This was because the next expected event was being set *after* the handling of the event, so the handling errored and returned, but the next expected event wasn't updated to be `EventContractReady`.
This PR updates the behaviour and fixes that bug. This is also more correct since the stage should definitely be updated once locking occurs.
=> fix: ensure stage is changed if funds are locked, even in error case

scripts/run-integration-tests.sh, tests/integration_test.go
Hopefully, the title is true. It does appear to have fixed the issue for me locally.
Closes 332.  To figure out the issue, I added a unit test here:
https://github.com/AthanorLabs/go-p2p-net/pull/2
=> fixed the TestAbort_ERC20_XMRMakerCancels issue

codecov.yml
When we switched to `codecov-action@v3` in https://github.com/AthanorLabs/atomic-swap/pull/334, it, inadvertently, enabled PR gating. We may want to enable it at some point, but it will require a more fine-tuned Codecov configuration. These configuration changes should keep the default Codecov commentary, but disable the PR gating.
=> prevent PR gating by codecov

net/message/message.go, protocol/xmrmaker/event.go, protocol/xmrmaker/event_test.go, protocol/xmrmaker/instance_test.go, protocol/xmrmaker/message_handler.go, protocol/xmrmaker/swap_state.go, protocol/xmrmaker/swap_state_ongoing_test.go, protocol/xmrmaker/swap_state_test.go, protocol/xmrtaker/errors.go, protocol/xmrtaker/event.go, protocol/xmrtaker/event_test.go, protocol/xmrtaker/message_handler.go, protocol/xmrtaker/swap_state.go, protocol/xmrtaker/swap_state_test.go
as title says, we don't need to worry about the balance unlock time anymore either, as the xmrtaker only notifies itself of the event `EventXMRLocked` once the unlocked balance is >= the expected amount to receive.
closes #335
=> remove `NotifyXMRLocked` message, have xmrtaker check for lock independently

cmd/swapcli/main.go, common/types/hash.go, docs/local.md, docs/rpc.md, rpc/swap.go, rpcclient/swap.go
- update `swap_getPast` to match `swap_getOngoing`'s behaviour; returns all past swaps if no ID is provided
- remove `swap_getPastIDs`
- update `swapcli get-past-swaps` -> `swapcli past` and `swapcli get-ongoing-swaps` -> `swapcli ongoing` (I think this is clearer and less to type out)
- update docs
closes #349
=> update `swap_getPast` to match `swap_getOngoing`; update docs

README.md, cliutil/utils.go, common/config.go, common/consts.go, common/network_test.go, docs/stagenet.md, ethereum/check_swap_factory_contract_test.go, ethereum/extethclient/eth_wallet_client.go, ethereum/extethclient/eth_wallet_client_test.go, pricefeed/pricefeed.go, scripts/setup-stagenet.sh
with this PR, we'll be using Sepolia for testnet/stagenet instead of Goerli. It's a lot easier to get SepETH and the public endpoints are more reliable. I've personally been using the PoW faucet.
closes #359
=> move stagenet from goerli to sepolia

cmd/swapcli/main.go, docs/rpc.md, protocol/xmrtaker/errors.go, protocol/xmrtaker/instance.go, protocol/xmrtaker/instance_test.go, protocol/xmrtaker/swap_state.go, rpc/errors.go, rpc/server.go, rpc/swap.go, rpcclient/swap.go
These two functions essentially did the same thing, except `swap_refund` was xmrtaker-only.
=> remove `swap_refund` in favour of `swap_cancel`

ethereum/watcher/watcher.go, protocol/xmrmaker/watcher.go
as title says, the reason we were seeing a bad log was because the event watcher was checking the same block twice, thus triggering the `Claimed` event handler twice, resulting in duplicate `EventETHClaimed` events
closes #381
=> fix: update event watcher to not checks blocks twice

daemon/double_restart_test.go, daemon/test_support.go, protocol/xmrtaker/claim.go, protocol/xmrtaker/swap_state.go, rpc/swap.go
as title says, `generateAndSetKeys` should NOT have been called when restarting an ongoing swap state, as it overwrote the keys in the db. this would have only been an issue on xmrtaker double-restart during a swap.
added a unit test for this case, and also added a small fix for a case caught in the test in `xmrtaker.swapState.ready()`
=> fix xmrtaker key overwrite on restart

cmd/swapcli/main.go, daemon/double_restart_test.go, daemon/manual_tx_test.go, protocol/xmrtaker/swap_state.go, rpc/mocks_test.go, rpc/server.go, rpc/swap.go, rpcclient/database.go, rpcclient/swap.go
new functions:
```
claim                    manually call claim() in the contract for a given swap. WARNING: This should only be used if the normal swap process fails.
refund                   manually call refund() in the contract for a given swap. WARNING: This should only be used if the normal swap process fails.
get-contract-swap-info   Get information about a swap needed to call the contract functions. Returns the contract address, the swap's struct as represented in the contract, and the hash of the swap's struct, which is used as its contract identifier. Note: this is only useful if you plan to manually call the contract functions.
get-swap-secret          Get the secret for a swap. WARNING: do NOT share this secret with anyone. Doing so may result in a loss of funds. You should …
```
=> feat: swapcli commands to manually claim/refund and for database functions

cmd/swapd/main.go, common/config.go, common/consts.go, daemon/manual_tx_test.go, daemon/test_support.go, ethereum/block/wait_for_timestamp_test.go, ethereum/extethclient/test_support.go, protocol/xmrmaker/instance_test.go, scripts/install-lint.sh, tests/ganache.go
This PR uses our environment config to set the ETH endpoint defaults for dev and stagenet. For mainnet, instead of giving an error because the code cannot connect to the default ganache port on localhost, we tell them that they need to set the endpoint.
Notable change: Our tests are using the http endpoint starting with this PR instead of the ws endpoint.
=> eth endpoint defaults and error handling

daemon/test_support.go, ethereum/check_swap_creator_contract_test.go, ethereum/consts.go, ethereum/consts_test.go, ethereum/deploy_util.go, ethereum/swap_creator_test.go, ethereum/test_support.go, protocol/xmrmaker/message_handler.go, protocol/xmrmaker/message_handler_test.go, protocol/xmrmaker/swap_state.go, relayer/claim_request_test.go, relayer/submit_transaction_test.go, relayer/validate_test.go, tests/ganache.go
Adds a new  `waitForNewSwapReceipt` method for when the maker receives the `NewSwap` TX has from the taker. The maker might not see the TX as having been minded into a block immediately even if the taker already saw it.
Consolidates test code for deploying the swap creator contract.
=> added new waitForNewSwapReceipt method for xmrmaker

protocol/xmrmaker/message_handler.go, protocol/xmrmaker/swap_state.go
similar issue to the xmrtaker, the timeout handler wasn't being started on restart
=> fix: run t1 handler on xmrmaker ongoing swap restart

protocol/xmrmaker/claim.go
for some reason, although I had more than enough funds to claim, I still got an `insufficient funds` error. this PR updates the code to handle that case, and use a relayer if we're out of funds
=> fix: handle "insufficient funds" error on claim

rpc/prometheus.go, rpc/server.go
closes #240
Adds the following prometheus metrics
```shell
swapdaemon_avg_swap_duration_seconds 18
swapdaemon_balance{coin="eth"} 1.0000985748404711e+21
swapdaemon_balance{coin="xmr"} 2.251284930376617e+15
swapdaemon_ongoing_swaps_count 0
swapdaemon_owned_offers_count 0
swapdaemon_past_swaps_count{status="abort"} 0
swapdaemon_past_swaps_count{status="refund"} 0
swapdaemon_past_swaps_count{status="success"} 1
swapdaemon_peers_count 2
```
The `Metrics` returned by  `SetupMetrics` is currently not used, but could be useful if we add metrics that are not determined at collect time.
=> add prometheus metrics

rpc/net.go
The `query-all` command to `swapcli` was reporting nodes that had presumably offered XMR at some point, but didn't have any current offers. This PR just prunes nodes with no offers from the returned results.
=> query-all no longer reports peers with no current offers

protocol/xmrtaker/errors.go, protocol/xmrtaker/net.go, protocol/xmrtaker/net_test.go, rpcclient/ws_methods.go
The taker over/under error messages were printing "ETH" even when the provided asset was a token.
=> fixed taker ERC20 over/under error messages

daemon/swap_daemon.go, docs/default-file-locations.md
In https://github.com/AthanorLabs/atomic-swap/pull/480, we upgraded `github.com/ChainSafe/chaindb` from the non-released commit hash `f900218c88f8` above release `v0.1.4` of  to a release that Chainsafe made 2 weeks ago tagged [v0.1.5](https://github.com/ChainSafe/chaindb/releases/tag/v0.1.5). The release tag is only changing the patch-level, so it should have been backwards compatible, but, sadly, it is not.
The `v0.1.5` chaindb release moves to [Badger v4.1.0](https://github.com/dgraph-io/badger/releases/tag/v4.1.0),  whose primary purpose is to fix 6 CVE's.
Attempting to run `swapd` with an existing database already in place gives this error:
```text
FATAL   cmd     swapd/main.go:228       manifest has unsupported version: 7 (we support 8).
Please see …
```
=> renamed swap database directory

cmd/swapcli/main.go, pricefeed/pricefeed.go, pricefeed/pricefeed_test.go
Someone put up a mainnet swap with an exchange rate of 0.1. I realized that our help could be clearer and while our code commentary in various places was correct on the numerator/denominator labeling, the swapcli output had it backwards.
=> exchange rate labeling updates

cmd/swapcli/main.go, common/consts.go, pricefeed/pricefeed.go, pricefeed/pricefeed_test.go
* Restores our suggested exchange rate ("price feed"), which broke when Chainlink removed the ETH mainnet feed for Monero. New version uses the Chainlink feed on Optimism.
* Minor tweaks to the swapcli flag aliases and help
Closes #492
=> restore price feed

.github/workflows/checks.yml, .github/workflows/unit-tests.yml, Makefile, pricefeed/pricefeed.go, pricefeed/pricefeed_test.go
The initial Optimism endpoint that I picked, `https://1rpc.io/op`, has degraded. It now, on a semi-regular basis, just returns an EOF error. (Worse than other endpoints, that give a message about being over the rate limit or a connection-refused error.)
This PR picks a different endpoint, from `blockpi`, and also makes the optimism endpoint configurable via an `ETH_OPTIMISM_ENDPOINT` environment variable. The naming of the variable was picked to match the unit test variables for Sepolia and Mainnet, and this new variable can also be set in the github secrets for CI.
Note that this variable name does not match the CLI environment variables that can be used in place of a CLI flag. If we don't end up finding a reliable endpoint, we may want to add full CLI support for setting the endpoint …
=> made optimism endpoint configurable and changed default
